lab_2: hamming_distance_calculator.s hamming_distance_driver.c 
	gcc -no-pie hamming_distance_calculator.s hamming_distance_driver.c -o lab_2

test: hamming_distance_calculator.s hamming_distance_tester.c 
	gcc -no-pie hamming_distance_calculator.s hamming_distance_tester.c -o lab_2_test



debug: hamming_distance_calculator.s hamming_distance_driver.c 
	gcc -g -no-pie hamming_distance_calculator.s hamming_distance_driver.c -o lab_2_debug

